In [1]:
import numpy as np

g = np.array([[1,0,0,0,0,0,0,0,1,1,0,0],[0,1,0,0,0,0,0,0,1,0,1,0],[0,0,1,0,0,0,0,0,0,1,1,0],[0,0,0,1,0,0,0,0,1,1,1,0],[0,0,0,0,1,0,0,0,1,0,0,1],[0,0,0,0,0,1,0,0,0,1,0,1],[0,0,0,0,0,0,1,0,1,1,0,1],[0,0,0,0,0,0,0,1,0,0,1,1]])
print('Generation matrix')
print(g)

Generation matrix
[[1 0 0 0 0 0 0 0 1 1 0 0]
 [0 1 0 0 0 0 0 0 1 0 1 0]
 [0 0 1 0 0 0 0 0 0 1 1 0]
 [0 0 0 1 0 0 0 0 1 1 1 0]
 [0 0 0 0 1 0 0 0 1 0 0 1]
 [0 0 0 0 0 1 0 0 0 1 0 1]
 [0 0 0 0 0 0 1 0 1 1 0 1]
 [0 0 0 0 0 0 0 1 0 0 1 1]]


In [2]:
h = np.array([[1,1,0,1,1,0,1,0,1,0,0,0],[1,0,1,1,0,1,1,0,0,1,0,0],[0,1,1,1,0,0,0,1,0,0,1,0],[0,0,0,0,1,1,1,1,0,0,0,1]])
print('H')
print(h)

H
[[1 1 0 1 1 0 1 0 1 0 0 0]
 [1 0 1 1 0 1 1 0 0 1 0 0]
 [0 1 1 1 0 0 0 1 0 0 1 0]
 [0 0 0 0 1 1 1 1 0 0 0 1]]


In [3]:
print('test G.H')
print(np.dot(h,np.transpose(g))%2)

test G.H
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [4]:
m = np.array([1,0,0,1,1,0,1,1])
print('message = ',m)
c = np.dot(m,g)%2
print('coded = ',c)
print('coded = mesage  + parity')
print(c[:8],' + ',c[8:])

message =  [1 0 0 1 1 0 1 1]
coded =  [1 0 0 1 1 0 1 1 0 1 0 1]
coded = mesage  + parity
[1 0 0 1 1 0 1 1]  +  [0 1 0 1]


In [5]:
print('received = ',c)
r = np.dot(h,c)%2
print(r,'no error detected')
er_c = np.array([1,0,1,1,1,1,0,1,1])

received =  [1 0 0 1 1 0 1 1 0 1 0 1]
[0 0 0 0] no error detected


In [12]:
er_c = np.array([1, 0 ,0 ,1, 0 ,0 ,1, 1, 0 ,1, 0, 1])
print('received with error = ',er_c)
er_r = np.dot(h,er_c)%2
print(er_r,'error detected')


received with error =  [1 0 0 1 0 0 1 1 0 1 0 1]
[1 0 0 1] error detected


In [13]:
for i in range(h.shape[1]):
        if np.array_equal(h[:,i] , er_r):
            print('error in position: ',i)
            er_c[i] = (er_c[i] + 1)%2
            break
print('corected message = ',er_c)

error in position:  4
corected message =  [1 0 0 1 1 0 1 1 0 1 0 1]
